import React from "react";
import Header from "./header";
import Footer from "./footer";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./styles.css";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <Header logo="https://cdn.builder.io/api/v1/image/assets/TEMP/c27b60d120448074aed912247ab433263e4e1bd5df6274db6626f4ae7ee5b0fe?apiKey=91998ea75a1643428fb73495d3983bc8&&apiKey=91998ea75a1643428fb73495d3983bc8" />
        {children}
        <Footer />
      </body>
    </html>
  );
}
